### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by TheRadziu** [Rinnegatamante/TrackPlug#2]
The plugin simply stopped working. It used to work, but probably around henkaku r9/r10 or enso update it simply stopped. At first I thought it was because I moved it to ur0:/tai (and edited config to point there), but it still doesnt work if placed in ux0. Tried with various games that used to work with, but no results. 
Even tried removing TrackPlug folder from data, but nothing is being recreated, and no time is being saved. 

My suspicion: the plugin is not compressed which is required since one of the henkaku updates.

**Comment by Rinnegatamante** [comment]
Try to replace kuio.skprx with the new one released few days ago (from VitaDB)

**Comment by TheRadziu** [comment]
It turned out that somehow I forgot about adding kuio to my new config file while I was recreating it despite having the file in tai. That was the main reason it wasn't working. 

At least I got informed about kuio's update and updated my plugin, that is nice bonus for this useless issue report :D
